#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export KEYTIMEOUT=1

#export PATH=$(cope_path):$PATH:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/core_perl
export PATH=$GOPATH/bin:/usr/lib/ccache:/home/yuchen/nfs/nginx-cache/lua/nginx/objs:$PATH
alias ga='git add'
alias cd..="cd .."
alias ya='PAGER="less -R" yaourt --pager --color'
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
zstyle ':completion:*' preserve-prefix '/afs/[^/]##/' # no excess stat'ing /afs
zstyle ':completion:*' accept-exact-dirs true # avoid excess stat'ing /afs
# Use - for the dir on the top
setopt pushdminus
