#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export KEYTIMEOUT=1
source /usr/local/bin/virtualenvwrapper.sh
#export PATH=$(cope_path):$PATH:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/core_perl
export PATH="/Users/yuchen/anaconda2/bin:$PATH"
alias ga='git add'
alias cd..="cd .."
alias ya='PAGER="less -R" yaourt --pager --color'
alias go='google -n 3 -C'
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
zstyle ':completion:*' preserve-prefix '/afs/[^/]##/' # no excess stat'ing /afs
zstyle ':completion:*' accept-exact-dirs true # avoid excess stat'ing /afs
# Use - for the dir on the top
setopt pushdminus
export TERM=xterm-256color
bindkey "^[[1~" beginning-of-line
bindkey "^[[4~" end-of-line
